### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by seemenkina**

### CODE REVIEW

**Review by rymnc — APPROVED** [review]
lgtm, thank you for covering the tech debt I left

**Comment by rymnc** [comment]
I'd suggest running the nightly workflow on this branch and confirming the archives :)

**Comment by seemenkina** [comment]
@rymnc I've already done it 

https://github.com/vacp2p/stealth-address-kit/actions/runs/11741556196

**Comment by rymnc** [comment]
nice!

**Pull request merged**
